version: '3'

services:
  db:
    image: mysql:5.7.26
    restart: always
    env_file:
      - .env
    ports:
      - "3306:3306"
    command: ['mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci']
    logging:
      driver: "json-file"
      options:
        max-file: '5'
        max-size: '10m'
  web:
    build: .
    command: sh -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    restart: always
    env_file:
      - .env
    ports:
      - "80:8000"
    volumes:
      - ./:/code
    depends_on:
      - db
    logging:
      driver: "json-file"
      options:
        max-file: '5'
        max-size: '10m'
  freeradius:
    build: ./freeradius/
    restart: always
    env_file:
      - .env
    ports:
      - "1812:1812/udp"
      - "1813:1813/udp"
    depends_on:
      - db
      - web
    logging:
      driver: "json-file"
      options:
        max-file: '5'
        max-size: '10m'
  flow-collector:
    build: ./flow-collector
    restart: always
    ports:
      - "555:555/udp"
    env_file:
      - .env
    logging:
      driver: "json-file"
      options:
        max-file: '5'
        max-size: '10m'
