# Generated by Django 2.2.2 on 2019-09-10 09:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=64, verbose_name='username')),
                ('telephone', models.CharField(max_length=255, verbose_name='Телефон')),
                ('title', models.CharField(max_length=150, verbose_name='Заголовок')),
                ('description', models.TextField(blank=True, verbose_name='Текст')),
                ('date_pub', models.DateTimeField(auto_now_add=True, verbose_name='Дата публикации')),
            ],
            options={
                'ordering': ['-date_pub'],
            },
        ),
        migrations.AlterModelOptions(
            name='authlog',
            options={'verbose_name': 'Лог авторизации', 'verbose_name_plural': 'Логи авторизации'},
        ),
        migrations.AlterModelOptions(
            name='building',
            options={'verbose_name': 'Корпус', 'verbose_name_plural': 'Корпусы'},
        ),
        migrations.AlterModelOptions(
            name='client',
            options={'verbose_name': 'Клиент', 'verbose_name_plural': 'Клиенты'},
        ),
        migrations.AlterModelOptions(
            name='clientparameter',
            options={'verbose_name': 'Параметры клиента', 'verbose_name_plural': 'Параметры клиентов'},
        ),
        migrations.AlterModelOptions(
            name='clientreply',
            options={'verbose_name': 'Настройки клиента', 'verbose_name_plural': 'Настройки клиентов'},
        ),
        migrations.AlterModelOptions(
            name='faculty',
            options={'verbose_name': 'Факультет', 'verbose_name_plural': 'Факультеты'},
        ),
        migrations.AlterModelOptions(
            name='group',
            options={'verbose_name': 'Учебная группа', 'verbose_name_plural': 'Учебные группы'},
        ),
        migrations.AlterModelOptions(
            name='groupparameter',
            options={'verbose_name': 'Параметры группы', 'verbose_name_plural': 'Параметры групп'},
        ),
        migrations.AlterModelOptions(
            name='groupreply',
            options={'verbose_name': 'Настройки группы', 'verbose_name_plural': 'Настройки групп'},
        ),
        migrations.AlterModelOptions(
            name='nas',
            options={'verbose_name': 'Роутер', 'verbose_name_plural': 'Роутеры'},
        ),
        migrations.AlterModelOptions(
            name='session',
            options={'verbose_name': 'Сессия', 'verbose_name_plural': 'Сессии'},
        ),
        migrations.AlterModelOptions(
            name='usergroup',
            options={'verbose_name': 'Группа клиента', 'verbose_name_plural': 'Группы клиентов'},
        ),
        migrations.RemoveField(
            model_name='client',
            name='telephone',
        ),
        migrations.RemoveField(
            model_name='nas',
            name='faculty',
        ),
        migrations.RemoveField(
            model_name='nas',
            name='user',
        ),
        migrations.AddField(
            model_name='client',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='panel.Group', verbose_name='Группа'),
        ),
        migrations.AddField(
            model_name='nas',
            name='mac',
            field=models.CharField(max_length=50, null=True, verbose_name='MAC'),
        ),
        migrations.AlterField(
            model_name='building',
            name='address',
            field=models.CharField(max_length=255, verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='building',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='client',
            name='faculty',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='panel.Faculty', verbose_name='Факультет'),
        ),
        migrations.AlterField(
            model_name='client',
            name='firstname',
            field=models.CharField(blank=True, max_length=255, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='client',
            name='lastname',
            field=models.CharField(blank=True, max_length=255, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='client',
            name='patronymic',
            field=models.CharField(blank=True, max_length=255, verbose_name='Отчество'),
        ),
        migrations.AlterField(
            model_name='client',
            name='status',
            field=models.CharField(blank=True, max_length=255, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='building',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='panel.Building', verbose_name='Корпус'),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='group',
            name='name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='nas',
            name='building',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='panel.Building', verbose_name='Корпус'),
        ),
        migrations.AlterField(
            model_name='nas',
            name='ip',
            field=models.CharField(max_length=15, verbose_name='IP'),
        ),
        migrations.AlterField(
            model_name='nas',
            name='name',
            field=models.CharField(max_length=32, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='nas',
            name='ports',
            field=models.IntegerField(null=True, verbose_name='Порт'),
        ),
        migrations.AlterField(
            model_name='nas',
            name='secret',
            field=models.CharField(max_length=60, verbose_name='Токен'),
        ),
        migrations.AlterField(
            model_name='nas',
            name='server',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Сервер'),
        ),
        migrations.AlterField(
            model_name='nas',
            name='type',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Тип'),
        ),
        migrations.CreateModel(
            name='Flow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unix_secs', models.IntegerField(default=0)),
                ('exaddr', models.CharField(default='0', max_length=45)),
                ('srcaddr', models.CharField(default='0', max_length=45)),
                ('dstaddr', models.CharField(default='0', max_length=45)),
                ('srcport', models.IntegerField(default=0)),
                ('dstport', models.IntegerField(default=0)),
                ('prot', models.IntegerField(default=0)),
            ],
            options={
                'unique_together': {('unix_secs', 'srcaddr', 'dstaddr', 'srcport', 'dstport')},
            },
        ),
    ]
