# Generated by Django 2.2.1 on 2019-05-19 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0003_remove_nas_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='nas',
            name='mac',
            field=models.CharField(default=None, max_length=50),
            preserve_default=False,
        ),
    ]
