# Generated by Django 2.2.1 on 2019-05-20 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0005_flow'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flow',
            name='dflows',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
