# Generated by Django 2.2.1 on 2019-05-20 04:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0006_auto_20190520_0356'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='flow',
            unique_together={('unix_secs', 'srcaddr', 'dstaddr', 'srcport', 'dstport')},
        ),
    ]
