# Generated by Django 2.2.1 on 2019-06-12 05:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0008_auto_20190612_0849'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='sms_auth',
            field=models.BooleanField(default=False, verbose_name='СМС авторизация'),
        ),
        migrations.AlterField(
            model_name='client',
            name='faculty',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='panel.Faculty', verbose_name='Факультет'),
        ),
        migrations.AlterField(
            model_name='client',
            name='firstname',
            field=models.CharField(blank=True, max_length=255, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='client',
            name='lastname',
            field=models.CharField(blank=True, max_length=255, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='client',
            name='patronymic',
            field=models.CharField(blank=True, max_length=255, verbose_name='Отчество'),
        ),
        migrations.AlterField(
            model_name='client',
            name='status',
            field=models.CharField(blank=True, max_length=255, verbose_name='Статус'),
        ),
    ]
