# Generated by Django 2.2.2 on 2019-06-12 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0009_auto_20190612_1011'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flow',
            name='dflows',
        ),
        migrations.RemoveField(
            model_name='flow',
            name='doctets',
        ),
        migrations.RemoveField(
            model_name='flow',
            name='dpkts',
        ),
        migrations.RemoveField(
            model_name='flow',
            name='dst_mask',
        ),
        migrations.RemoveField(
            model_name='flow',
            name='engine_id',
        ),
        migrations.RemoveField(
            model_name='flow',
            name='engine_type',
        ),
        migrations.RemoveField(
            model_name='flow',
            name='first',
        ),
        migrations.RemoveField(
            model_name='flow',
            name='input',
        ),
        migrations.RemoveField(
            model_name='flow',
            name='last',
        ),
        migrations.RemoveField(
            model_name='flow',
            name='nexthop',
        ),
        migrations.RemoveField(
            model_name='flow',
            name='output',
        ),
        migrations.RemoveField(
            model_name='flow',
            name='src_mask',
        ),
        migrations.RemoveField(
            model_name='flow',
            name='sysuptime',
        ),
        migrations.RemoveField(
            model_name='flow',
            name='tcp_flags',
        ),
        migrations.RemoveField(
            model_name='flow',
            name='tos',
        ),
        migrations.RemoveField(
            model_name='flow',
            name='unix_nsecs',
        ),
    ]
