# Generated by Django 2.2.2 on 2019-06-13 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0010_auto_20190612_2159'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Group',
        ),
    ]
